site_name: RISC-V PVP

repo_name: ultrafive/riscv-pvp
repo_url: https://github.com/ultrafive/riscv-pvp

copyright: Copyright &copy; 2021 - 2021 Stream Computing Corp.

theme:
  name: "material"
  features:
    - navigation.sections

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - mkdocs-click
  
nav:
  - Overview: index.md
  - Getting Started: get-started.md
  - Support New Targets: new-target.md
  - Developing Guide: developing.md
  - Reference:
    - Command Line: reference/cli.md
    - Cases: reference/spec.md
    - Functions:
       - Test Data: reference/functions/data.md
       - Utilities: reference/functions/utils.md

extra_css:
  - assets/style.css
