processor:
  xlen: 64
  flen: 64
  vlen: 1024
  elen: 64
  slen: 1024

compile:
  path: clang
  cc: f'{path} --target=riscv{xlen}-unknown-elf -mno-relax -fuse-ld=lld -march=rv{xlen}gv0p10zfh0p1 -menable-experimental-extensions'
  defines: f'-DXLEN={xlen} -DVLEN={vlen}'
  cflags: -g -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles
  incs: -Ienv/p -Imacros/scalar -Imacros/vector -Imacros/stc
  linkflags: -Tenv/p/link.ld
  objdump: riscv64-unknown-elf-objdump -S -D
  is_objdump: True
  readelf: riscv64-unknown-elf-readelf

lsf:
  cmd: bsub -n 1 -J simv -Ip
  is_flag: False

spike:
  path: spike
  cmd: f'{path} --isa=rv{xlen}gcv_zfh --varch=vlen:{vlen},elen:{elen},slen:{slen}'

gem5:
  path: ~
  options: |
      --debug-flags=Exec \
      --listener-mode=off \
       ~/work/gem5/gem5/configs/example/fs.py \
      --cpu-type=MinorCPU \
      --bp-type=LTAGE \
      --num-cpu=1 \
      --mem-channels=1 \
      --mem-size=3072MB \
      --caches \
      --l1d_size=32kB \
      --l1i_size=32kB \
      --cacheline_size=64 \
      --l1i_assoc=8 \
      --l1d_assoc=8 \
      --l2cache \
      --l2_size=512kB \

vcs:
  path: ../../../sims/vcs/simv-chipyard-StcBoomConfig-debug
  vcstimeout: 1000000
  fsdb: False
  tsiloadmem: False


verilator:
  path: ~  
